run:
  concurrency: 4
  timeout: 5m
  skip-dirs:
    - skip-dir-name
  skip-files:
    - assets/assets.go

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

issues:
  max-same-issues: 3
  new: false

linters:
  enable-all: true
  disable:
    - errcheck # 因开发暂停
    - gochecknoinits
    - gochecknoglobals
    - interfacer
    - unused
    - unparam
    - gci # 因bug暂停
    - gosec
    - godox
    - maligned
    - nlreturn
    - wsl
    - godot

linters-settings:
  gocritic:
    enabled-tags:
      - performance
      - opinionated
      - diagnostic
    disabled-checks:
      - paramTypeCombine
      - unnamedResult
    settings:
      hugeParam:
        sizeThreshold: 512
      rangeValCopy:
        sizeThreshold: 512
        skipTestFuncs: true
  varnamelen:
    min-name-length: 1
